services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:42v1.0
    ports:
      - "443:443"
    restart: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:42v1.0
    env_file: .env
    ports:
      - "3306:3306"
    restart: always
    networks:
      - inception
    depends_on:
      - nginx
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./requirements/mariadb/conf/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf:ro

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:42v1.0
    env_file: .env
    ports:
      - "9000:9000"
    restart: always
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress-data:/var/www/html/ialves-m/wordpress/

networks:
  inception:
    name: inception_network
    driver: bridge

volumes:
  mariadb-data:
    name: mariadb_volume
    driver: local
    driver_opts:
      type: none
      device: /home/ialves-m/db
      o: bind
  wordpress-data:
    name: wordpress_volume
    driver: local
    driver_opts:
      type: none
      device: /home/ialves-m/wp
      o: bind