services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:42v1.0
    ports:
      - "443:443"
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:42v1.0
    env_file: ./.env
    ports:
      - "3306:3306"
    restart: always
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:42v1.0
    env_file: ./.env
    ports:
      - "9000:9000"
    restart: always


