version: '3.8'

services:
  nginx:
    image: nginx:v42
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html

  mariadb:
    image: mariadb:v42
    container_name: mariadb
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    command: mysqld --skip-networking=0 --socket=/run/mysqld/mysqld.sock

volumes:
  mariadb_data:
