services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: ./.env
    ports:
      - "3306:3306"
    